name: AdvancedItemEffectsPE
main: AdvancedItemEffectsPE\Main
version: 1.0.0
api: [1.2.0]

load: POSTWORLD
authors: [ace]
description: AdvancedItemEffectsPE
commands:
 aie:
  permission: AdvancedItemEffects.command
  description: AdvancedItemEffects command
permissions:
 AdvancedItemEffects.command:
  default: op